import { join } from 'node:path';
import semver from 'semver';
import { getNodeEngine, readPackageJson } from '../scanner/package-json.js';
import type { ProductType } from '../types/profile.js';
import { fileExists, readText } from '../utils/fs.js';

/**
 * Draft a project-profile YAML from a repo's package.json, README, and layout
 * (PLAN §7 "Profile 生成"). Best-effort guesses only — EVERY field is tagged
 * `# NEEDS REVIEW` because a wrong profile skews all recommendations. The output
 * is valid YAML that `parseProfile` accepts; it is purely a starting point for
 * the human review the spec mandates. Deterministic for a given repo state.
 */
export function draftProfileYaml(repoPath: string): string {
  const pkg = readPackageJson(join(repoPath, 'package.json'));
  const hasApps = fileExists(join(repoPath, 'apps'));
  const hasPackages = fileExists(join(repoPath, 'packages'));
  const readme = readReadme(repoPath);

  const productType = inferProductType(pkg, { hasApps, hasPackages, readme });
  // Only carry engines.node forward when it's a valid range — a malformed value
  // would otherwise make the draft fail its own parseProfile self-check.
  const rawNode = pkg ? getNodeEngine(pkg) : null;
  const node = rawNode && semver.validRange(rawNode) !== null ? rawNode : null;

  const REVIEW = '# NEEDS REVIEW';
  // The header deliberately writes the token as "NEEDS REVIEW" without a leading
  // '#', so it does NOT trip the unreviewed check — only the per-field markers do.
  // That way, deleting the field markers fully clears the warning.
  return [
    '# Stack Radar project profile — generated by `init-profile`.',
    '# A wrong profile skews every recommendation: review each value below, then',
    '# delete the trailing "NEEDS REVIEW" comments. (All comments are ignored by the parser.)',
    '',
    `product_type: ${productType}          ${REVIEW} — component_library | business_app | internal_tool | sdk`,
    `users_and_scale: internal             ${REVIEW} — internal | high_traffic_consumer | enterprise_b2b`,
    `tech_taste: mainstream                ${REVIEW} — conservative | mainstream | aggressive`,
    '',
    'hard_constraints:',
    `  node: ${node ? `"${node}"` : 'null'}                       ${REVIEW} — semver range the project must keep supporting, or null`,
    `  browser_support: null               ${REVIEW} — free text, e.g. "Chrome 100+, Safari 15+"`,
    `  a11y: null                          ${REVIEW} — free text, e.g. "WCAG 2.1 AA"`,
    `  compliance: []                      ${REVIEW} — e.g. [SOC2, HIPAA]`,
    '',
    `current_pain_points: []               ${REVIEW} — e.g. ["build time too slow", "TS type check slow"]`,
    '',
    'upgrade_policy:',
    `  major: manual_review                ${REVIEW} — manual_review | normal_queue | auto_candidate`,
    `  minor: normal_queue                 ${REVIEW} — manual_review | normal_queue | auto_candidate`,
    `  patch: auto_candidate               ${REVIEW} — manual_review | normal_queue | auto_candidate`,
    '',
  ].join('\n');
}

interface InferHints {
  hasApps: boolean;
  hasPackages: boolean;
  readme: string;
}

/** Heuristic product_type guess (always # NEEDS REVIEW downstream). */
function inferProductType(
  pkg: ReturnType<typeof readPackageJson>,
  { hasApps, hasPackages, readme }: InferHints,
): ProductType {
  const text = `${pkg?.description ?? ''} ${readme}`.toLowerCase();
  if (pkg?.bin) return 'internal_tool'; // ships an executable → a CLI/tool
  if (/\bsdk\b/.test(text)) return 'sdk';
  if (/component library|design system|ui kit|ui library/.test(text)) return 'component_library';
  if (hasApps) return 'business_app'; // apps/* workspace → app(s)
  if (hasPackages) return 'component_library'; // packages/* only → library monorepo
  return 'business_app'; // safest default for a single-package repo
}

/** First ~600 chars of the repo README (any common casing), or "". */
function readReadme(repoPath: string): string {
  for (const name of ['README.md', 'readme.md', 'README.MD', 'Readme.md']) {
    const text = readText(join(repoPath, name));
    if (text !== null) return text.slice(0, 600);
  }
  return '';
}
